from __future__ import annotations

from pathlib import Path
from typing import Any

import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms

from src.predictors.base import BasePredictor
from src.predictors.registry import PREDICTORS

IMAGENET_CLASSES = [
    "tench",
    "goldfish",
    "great white shark",
    "tiger shark",
    "hammerhead",
    "electric ray",
    "stingray",
    "cock",
    "hen",
    "ostrich",
    "brambling",
    "goldfinch",
    "house finch",
    "junco",
    "indigo bunting",
    "robin",
    "bulbul",
    "jay",
    "magpie",
    "chickadee",
    "water ouzel",
    "kite",
    "bald eagle",
    "vulture",
    "great grey owl",
    "salamander",
    "newt",
    "axolotl",
    "bullfrog",
    "tree frog",
    "tailed frog",
    "loggerhead",
    "leatherback turtle",
    "mud turtle",
    "terrapin",
    "box turtle",
    "banded gecko",
    "common iguana",
    "chameleon",
    "gila monster",
    "whiptail",
    "agama",
    "frilled lizard",
    "alligator lizard",
    "slow worm",
    "snake",
    "grass snake",
    "water snake",
    "vine snake",
    "night snake",
    "boa",
    "rock python",
    "cobra",
    "mamba",
    "sea snake",
    "horned viper",
    "diamondback",
    "sidewinder",
    "trilobite",
    "harvestman",
    "scorpion",
    "spider",
    "tarantula",
    "wolf spider",
    "tick",
    "centipede",
    "black grouse",
    "ptarmigan",
    "ruffed grouse",
    "prairie chicken",
    "peacock",
    "quail",
    "partridge",
    "african grey",
    "macaw",
    "cockatoo",
    "lorikeet",
    "coucal",
    "bee eater",
    "hornbill",
    "hummingbird",
    "jacamar",
    "toucan",
    "drake",
    "merganser",
    "goose",
    "black swan",
    "tusker",
    "echidna",
    "platypus",
    "wallaby",
    "koala",
    "wombat",
    "jellyfish",
    "sea anemone",
    "brain coral",
    "flatworm",
    "nematode",
    "conch",
    "snail",
    "slug",
    "sea slug",
    "chiton",
    "nautilus",
    "dungeness crab",
    "rock crab",
    "fiddler crab",
    "king crab",
    "lobster",
    "spiny lobster",
    "crayfish",
    "hermit crab",
    "isopod",
    "white stork",
    "black stork",
    "spoonbill",
    "flamingo",
    "little blue heron",
    "egret",
    "bittern",
    "crane",
    "bustard",
    "ruddy turnstone",
    "redshank",
    "dowitcher",
    "oystercatcher",
    "pelican",
    "king penguin",
    "albatross",
    "grey whale",
    "killer whale",
    "dugong",
    "sea lion",
    "chihuahua",
    "japanese spaniel",
    "maltese",
    "pekinese",
    "shih-tzu",
    "king charles spaniel",
    "papillon",
    "toy terrier",
    "rhodesian ridgeback",
    "afghan hound",
    "basset",
    "beagle",
    "bloodhound",
    "bluetick",
    "black-and-tan coonhound",
    "walker hound",
    "english foxhound",
    "redbone",
    "borzoi",
    "irish wolfhound",
    "italian greyhound",
    "whippet",
    "ibizan hound",
    "norwegian elkhound",
    "otterhound",
    "saluki",
    "scottish deerhound",
    "weimaraner",
    "staffordshire bullterrier",
    "staffordshire terrier",
    "bedlington terrier",
    "border terrier",
    "kerry blue terrier",
    "irish terrier",
    "norfolk terrier",
    "norwich terrier",
    "yorkshire terrier",
    "wire-haired fox terrier",
    "lakeland terrier",
    "sealyham terrier",
    "airedale",
    "cairn",
    "australian terrier",
    "dandie dinmont",
    "boston bull",
    "miniature schnauzer",
    "giant schnauzer",
    "standard schnauzer",
    "scotch terrier",
    "tibetan terrier",
    "silky terrier",
    "soft-coated wheaten terrier",
    "west highland white terrier",
    "lhasa",
    "flat-coated retriever",
    "curly-coated retriever",
    "golden retriever",
    "labrador retriever",
    "chesapeake bay retriever",
    "german short-haired pointer",
    "vizsla",
    "english setter",
    "irish setter",
    "gordon setter",
    "brittany spaniel",
    "clumber",
    "english springer",
    "welsh springer spaniel",
    "cocker spaniel",
    "sussex spaniel",
    "irish water spaniel",
    "kuvasz",
    "schipperke",
    "groenendael",
    "malinois",
    "briard",
    "kelpie",
    "komondor",
    "old english sheepdog",
    "shetland sheepdog",
    "collie",
    "border collie",
    "bouvier des flandres",
    "rottweiler",
    "german shepherd",
    "doberman",
    "miniature pinscher",
    "greater swiss mountain dog",
    "bernese mountain dog",
    "appenzeller",
    "entlebucher",
    "boxer",
    "bull mastiff",
    "tibetan mastiff",
    "french bulldog",
    "great dane",
    "saint bernard",
    "eskimo dog",
    "malamute",
    "siberian husky",
    "dalmatian",
    "affenpinscher",
    "basenji",
    "pug",
    "leonberg",
    "newfoundland",
    "great pyrenees",
    "samoyed",
    "pomeranian",
    "chow",
    "keeshond",
    "brabancon griffon",
    "pembroke",
    "cardigan",
    "toy poodle",
    "miniature poodle",
    "standard poodle",
    "mexican hairless",
    "timber wolf",
    "white wolf",
    "coyote",
    "dingo",
    "dhole",
    "african hunting dog",
    "hyena",
    "red fox",
    "kit fox",
    "arctic fox",
    "grey fox",
    "tabby",
    "tiger cat",
    "persian cat",
    "siamese cat",
    "egyptian cat",
    "cougar",
    "lynx",
    "leopard",
    "snow leopard",
    "jaguar",
    "lion",
    "tiger",
    "cheetah",
    "brown bear",
    "american black bear",
    "ice bear",
    "sloth bear",
    "mongoose",
    "meerkat",
    "tiger beetle",
    "ladybug",
    "ground beetle",
    "long-horned beetle",
    "leaf beetle",
    "dung beetle",
    "rhinoceros beetle",
    "weevil",
    "fly",
    "bee",
    "ant",
    "grasshopper",
    "cricket",
    "walking stick",
    "cockroach",
    "mantis",
    "cicada",
    "leafhopper",
    "lacewing",
    "dragonfly",
    "damselfly",
    "admiral",
    "ringlet",
    "monarch",
    "cabbage butterfly",
    "sulphur butterfly",
    "lycaenid",
    "starfish",
    "sea urchin",
    "sea cucumber",
    "wood rabbit",
    "hare",
    "angora",
    "hamster",
    "porcupine",
    "fox squirrel",
    "marmot",
    "beaver",
    "guinea pig",
    "sorrel",
    "zebra",
    "hog",
    "wild boar",
    "warthog",
    "hippopotamus",
    "ox",
    "water buffalo",
    "bison",
    "ram",
    "ibex",
    "hartebeest",
    "impala",
    "gazelle",
    "arabian camel",
    "llama",
    "weasel",
    "mink",
    "polecat",
    "black-footed ferret",
    "otter",
    "skunk",
    "badger",
    "armadillo",
    "sloth",
    "orangutan",
    "gorilla",
    "chimpanzee",
    "gibbon",
    "siamang",
    "proboscis monkey",
    "macaque",
    "patas",
    "baboon",
    "mandrill",
    "colobus",
    "langur",
    "proboscis monkey",
    "indri",
    "howler monkey",
    "marmoset",
    "white-headed capuchin",
    "spider monkey",
    "squirrel monkey",
    "moustached tamarin",
    "emperor tamarin",
    "titi",
    "saki",
    "uakari",
    "mouse",
    "hamster",
    "rat",
    "guinea pig",
    "chipmunk",
    "prairie dog",
    "bison",
    "ox",
    "wildebeest",
    "hartebeest",
    "topi",
    "gazelle",
    "springbok",
    "blackbuck",
    "impala",
    "dik-dik",
    "klipspringer",
    "duiker",
    "steenbok",
    "sable antelope",
    "oryx",
    "waterbuck",
    "kudu",
    "eland",
    "nilgai",
    "four-horned antelope",
    "takin",
    "musk ox",
    "pronghorn",
    "giraffe",
    "okapi",
    "eastern diamondback",
    "sidewinder",
    "horned viper",
    "cobra",
    "mamba",
    "green snake",
    "king snake",
    "garter snake",
    "water snake",
    "vine snake",
    "night snake",
    "indigo snake",
    "boomslang",
    "file snake",
    "trilobite",
    "harvestman",
    "scorpion",
    "black and gold garden spider",
    "barn spider",
    "garden spider",
    "black widow",
    "tarantula",
    "wolf spider",
    "tick",
    "centipede",
    "black grouse",
    "ptarmigan",
    "ruffed grouse",
    "prairie chicken",
    "peacock",
    "quail",
    "partridge",
    "african grey",
    "macaw",
    "sulphur-crested cockatoo",
    "lorikeet",
    "coucal",
    "bee eater",
    "hornbill",
    "hummingbird",
    "jacamar",
    "toucan",
    "drake",
    "red-breasted merganser",
    "goose",
    "black swan",
    "tusker",
    "echidna",
    "platypus",
    "wallaby",
    "koala",
    "wombat",
    "jellyfish",
    "sea anemone",
    "brain coral",
    "flatworm",
    "nematode",
    "conch",
    "snail",
    "slug",
    "sea slug",
    "chiton",
    "chambered nautilus",
    "dungeness crab",
    "rock crab",
    "fiddler crab",
    "king crab",
    "american lobster",
    "spiny lobster",
    "crayfish",
    "hermit crab",
    "isopod",
    "white stork",
    "black stork",
    "spoonbill",
    "flamingo",
    "little blue heron",
    "great egret",
    "bittern",
    "crane bird",
    "limpkin",
    "european gallinule",
    "american coot",
    "bustard",
    "ruddy turnstone",
    "red-backed sandpiper",
    "redshank",
    "dowitcher",
    "oystercatcher",
    "pelican",
    "king penguin",
    "albatross",
    "grey whale",
    "killer whale",
    "dugong",
    "sea lion",
    "chihuahua",
    "japanese spaniel",
    "maltese dog",
    "pekinese",
    "shih-tzu",
    "blenheim spaniel",
    "papillon",
    "toy terrier",
    "rhodesian ridgeback",
    "afghan hound",
    "basset",
    "beagle",
    "bloodhound",
    "bluetick",
    "black-and-tan coonhound",
    "walker hound",
    "english foxhound",
    "redbone",
    "borzoi",
    "irish wolfhound",
    "italian greyhound",
    "whippet",
    "ibizan hound",
    "norwegian elkhound",
    "otterhound",
    "saluki",
    "scottish deerhound",
    "weimaraner",
    "staffordshire bullterrier",
    "american staffordshire terrier",
    "bedlington terrier",
    "border terrier",
    "kerry blue terrier",
    "irish terrier",
    "norfolk terrier",
    "norwich terrier",
    "yorkshire terrier",
    "wire-haired fox terrier",
    "lakeland terrier",
    "sealyham terrier",
    "airedale",
    "cairn",
    "australian terrier",
    "dandie dinmont",
    "boston bull",
    "miniature schnauzer",
    "giant schnauzer",
    "standard schnauzer",
    "scotch terrier",
    "tibetan terrier",
    "silky terrier",
    "soft-coated wheaten terrier",
    "west highland white terrier",
    "lhasa",
    "flat-coated retriever",
    "curly-coated retriever",
    "golden retriever",
    "labrador retriever",
    "chesapeake bay retriever",
    "german short-haired pointer",
    "vizsla",
    "english setter",
    "irish setter",
    "gordon setter",
    "brittany spaniel",
    "clumber",
    "english springer",
    "welsh springer spaniel",
    "cocker spaniel",
    "sussex spaniel",
    "irish water spaniel",
    "kuvasz",
    "schipperke",
    "groenendael",
    "malinois",
    "briard",
    "kelpie",
    "komondor",
    "old english sheepdog",
    "shetland sheepdog",
    "collie",
    "border collie",
    "bouvier des flandres",
    "rottweiler",
    "german shepherd",
    "doberman",
    "miniature pinscher",
    "greater swiss mountain dog",
    "bernese mountain dog",
    "appenzeller",
    "entlebucher",
    "boxer",
    "bull mastiff",
    "tibetan mastiff",
    "french bulldog",
    "great dane",
    "saint bernard",
    "eskimo dog",
    "malamute",
    "siberian husky",
    "dalmatian",
    "affenpinscher",
    "basenji",
    "pug",
    "leonberg",
    "newfoundland",
    "great pyrenees",
    "samoyed",
    "pomeranian",
    "chow",
    "keeshond",
    "brabancon griffon",
    "pembroke",
    "cardigan",
    "toy poodle",
    "miniature poodle",
    "standard poodle",
    "mexican hairless",
    "timber wolf",
    "white wolf",
    "coyote",
    "dingo",
    "dhole",
    "african hunting dog",
    "hyena",
    "red fox",
    "kit fox",
    "arctic fox",
    "grey fox",
    "tabby",
    "tiger cat",
    "persian cat",
    "siamese cat",
    "egyptian mau",
    "cougar",
    "lynx",
    "leopard",
    "snow leopard",
    "jaguar",
    "lion",
    "tiger",
    "cheetah",
    "brown bear",
    "american black bear",
    "ice bear",
    "sloth bear",
    "mongoose",
    "meerkat",
    "tiger beetle",
    "ladybug",
    "ground beetle",
    "long-horned beetle",
    "leaf beetle",
    "dung beetle",
    "rhinoceros beetle",
    "weevil",
    "fly",
    "bee",
    "ant",
    "grasshopper",
    "cricket",
    "walking stick",
    "cockroach",
    "mantis",
    "cicada",
    "leafhopper",
    "lacewing",
    "dragonfly",
    "damselfly",
    "admiral",
    "ringlet",
    "monarch",
    "cabbage butterfly",
    "sulphur butterfly",
    "lycaenid",
    "starfish",
    "sea urchin",
    "sea cucumber",
    "wood rabbit",
    "hare",
    "angora",
    "hamster",
    "porcupine",
    "fox squirrel",
    "marmot",
    "beaver",
    "guinea pig",
    "sorrel",
    "zebra",
    "hog",
    "wild boar",
    "warthog",
    "hippopotamus",
    "ox",
    "water buffalo",
    "bison",
    "ram",
    "bighorn",
    "ibex",
    "hartebeest",
    "impala",
    "gazelle",
    "arabian camel",
    "llama",
    "weasel",
    "mink",
    "polecat",
    "black-footed ferret",
    "otter",
    "skunk",
    "badger",
    "armadillo",
    "three-toed sloth",
    "orangutan",
    "gorilla",
    "chimpanzee",
    "gibbon",
    "siamang",
    "guenon",
    "patas",
    "baboon",
    "macaque",
    "langur",
    "colobus",
    "proboscis monkey",
    "marmoset",
    "capuchin",
    "howler monkey",
    "titi",
    "spider monkey",
    "squirrel monkey",
    "madagascar cat",
    "indri",
    "woolly monkey",
    "mongoose lemur",
    "dwarf lemur",
    "aye-aye",
    "ring-tailed lemur",
    "sifaka",
    "indri",
    "tarsier",
    "marmoset",
    "tamarin",
    "spider monkey",
    "howler monkey",
    "squirrel monkey",
    "capuchin",
    "titi monkey",
    "saki monkey",
    "uakari",
    "night monkey",
    "woolly monkey",
    "spider monkey",
    "marmoset",
    "tamarin",
    "titi",
    "saki",
    "uakari",
    "proboscis monkey",
    "gibbon",
    "siamang",
    "orangutan",
    "gorilla",
    "chimpanzee",
    "bonobo",
    "human",
    "neanderthal",
    "homo erectus",
    "australopithecus",
]

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]


@PREDICTORS.register("classification")
class ClassificationPredictor(BasePredictor):
    def __init__(
        self,
        model: nn.Module,
        ckpt_path: str | Path | None = None,
        device: str = "cpu",
        experiment: Any = None,
        class_names: list[str] | None = None,
    ) -> None:
        super().__init__(model, ckpt_path=ckpt_path, device=device, experiment=experiment)

        if class_names is not None:
            self.class_names = class_names
        elif ckpt_path is not None:
            ckpt = torch.load(str(ckpt_path), map_location=self.device)
            self.class_names = ckpt.get("class_names") or ckpt.get("config", {}).get("class_names") or IMAGENET_CLASSES
        else:
            self.class_names = IMAGENET_CLASSES

        self.transform = transforms.Compose(
            [
                transforms.Resize(256),
                transforms.CenterCrop(224),
                transforms.ToTensor(),
                transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
            ]
        )

    def preprocess(self, raw_input: Image.Image) -> torch.Tensor:
        tensor = self.transform(raw_input)
        tensor = tensor.unsqueeze(0)
        return tensor.to(self.device)

    def postprocess(self, outputs: dict[str, Any]) -> dict[str, Any]:
        if isinstance(outputs, dict) and "logits" in outputs:
            logits = outputs["logits"]
        elif isinstance(outputs, dict):
            logits = next(v for v in outputs.values() if isinstance(v, torch.Tensor))
        else:
            logits = outputs

        if isinstance(logits, torch.Tensor):
            logits = logits.squeeze(0)

        probs = F.softmax(logits, dim=0)
        top5_probs, top5_indices = torch.topk(probs, min(5, len(probs)))

        top_class_idx = int(top5_indices[0].item())
        top_class_name = (
            self.class_names[top_class_idx] if top_class_idx < len(self.class_names) else f"class_{top_class_idx}"
        )

        top5 = [
            {
                "class_id": int(idx.item()),
                "class_name": (
                    self.class_names[int(idx.item())]
                    if int(idx.item()) < len(self.class_names)
                    else f"class_{int(idx.item())}"
                ),
                "confidence": float(conf.item()),
            }
            for idx, conf in zip(top5_indices, top5_probs)
        ]

        return {
            "class_id": top_class_idx,
            "class_name": top_class_name,
            "confidence": float(top5_probs[0].item()),
            "top5": top5,
        }

    def visualize(self, input_data: Image.Image, save_path: str | Path | None = None) -> Any:
        import matplotlib.pyplot as plt

        result = self.predict(input_data)
        top_class = result["class_name"]
        confidence = result["confidence"]

        fig, ax = plt.subplots(1, 1, figsize=(8, 8))
        ax.imshow(input_data)
        ax.set_title(f"{top_class} ({confidence:.3f})", fontsize=14)
        ax.axis("off")

        if save_path is not None:
            fig.savefig(save_path, bbox_inches="tight", dpi=150)
            plt.close(fig)

        return fig
